version: 0.2
FROM alpine:3.5

phases:
  install:
    commands:
      = RUN apk add --update py2-pip
      - COPY requirements.txt /usr/src/app/
      - RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt
  build:
    commands:
      - COPY app.py /usr/src/app/
      - COPY templates/index.html /usr/src/app/templates/
      - EXPOSE 5000
      - CMD ["python", "/usr/src/app/app.py"]
artifacts:
  files:
    - '**/*'
